# Generated by Django 5.0.6 on 2024-06-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
