# Generated by Django 5.0.6 on 2024-06-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_user_password_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curlocation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
