# Generated by Django 5.0.6 on 2024-06-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_user_curlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bucket',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='curlocation',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
