# Generated by Django 5.0.6 on 2024-06-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_chat', '0002_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
