# Generated by Django 5.0.6 on 2024-06-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_chat', '0003_alter_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
    ]
