# Generated by Django 5.0.6 on 2024-06-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.TextField(),
        ),
    ]
