# Generated by Django 5.0.6 on 2024-06-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_feed', '0002_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
